# Generated by Django 4.2.2 on 2023-06-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costomer',
            new_name='Customer',
        ),
    ]
